# Generated by Django 5.1.4 on 2024-12-16 22:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangledb',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='djangledb',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_djan_search__ee5ffc_gin'),
        ),
    ]
